source 'https://rubygems.org'

gem 'rails', '4.0.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
group :development do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
end

# Gems used only for assest and not required 
# in production envronments by default.
group :assets do
	gem 'sqlite3', '~> 3.2.3'
	gem 'coffee-rails', '~> 3.2.1'

	gem 'uglifier', '>= 1.0.3'
end